
enum class ErrorType {
	SYNTAX_ERROR,
	IMPLICIT_CAST_NOT_ALLOWED,
	TYPE_NOT_DEFINED,
	UNKNOWN_ERROR,
	NO_RETURN_ERROR,
	INVALID_OPERAND_TYPE,
	NO_MATCHING_FUNCTION,
	AMBIGUOUS_FUNCTION_CALL,
	ERROR_COUNT,
};
